config/routes.rb
# -*- encoding : utf-8 -*-
Sapphire::Application.routes.draw do

  match '/synchronisation', :to => "switchs_management#synchronisation"
  resources :logs


  resources :roles


	# En vrac
		get '/computers/reload', :controller => 'computers', :action => 'reload'
		resources :computers, :only => [:index, :show]

		get '/payments/reload', :controller => 'payments', :action => 'reload'
		resources :payments do
			member do
				get 'cash'
				get 'by_treasurer'
				get 'reset_status'
			end
		end

		# Sessions
		delete "deconnexion", to: "sessions#destroy", as: "deconnexion"
		get 'connexion', to: 'sessions#new', as: :connexion

		root to: "activities#index"

	# Les différentes ressources de l'appli

		resources :sessions
		resources :admins

		get '/mailings/reload', :controller => 'mailings', :action => 'reload'
		resources :mailings

		get '/rooms/reload', :controller => 'rooms', :action => 'reload'
		resources :rooms

		get '/adherents/reload', :controller => 'adherents', :action => 'reload'
		get '/adherents/index_discourse', :controller => 'adherents', :action => 'index_discourse'
		resources :adherents do
			member do
				get 'new_discourse'
				put 'create_discourse'
			end
			resources :computers
			resources :payments
			get "credit/destroy"
		end
		
		get '/generic_dns_entries/reload', :controller => 'generic_dns_entries', :action => 'reload'
	  	resources :generic_dns_entries
	  	resources :computer_dns_entries do
			resources :alias_dns_entries
		end
		resources :vlans

		get '/switches/reload', :controller => 'switches', :action => 'reload'
		resources :switches do
			resources :ports
		end
	
end

app/models/payment.rb
# -*- encoding : utf-8 -*-
class Payment < ActiveRecord::Base

scope :not_archived, -> { where(archived: false)}

# Surveillance par la gem public_activity
	include PublicActivity::Common

# Attributs et associations	

	attr_accessible :comment, :mean, :paid_value, :value, :bank_name, :cotisation

	belongs_to :credit, inverse_of: :payments
	belongs_to :admin, inverse_of: :payments
	has_one :adherent, through: :credit


# Validations

	validates :value, presence: true
	validates :paid_value, presence: true

	validates :comment, presence: true, unless: :equality_of_values

	validate :mean_is_correct
	validates :bank_name, presence: true, if: :mean_is_cheque

	validates :credit, presence: true
	validates :admin, presence: true

# Lors de la sauvegarde :
	after_save :update_credit

# Machine d'état

state_machine :state, initial: :received do

	after_transition all => :cashed, do: :set_cached_date

	event :by_treasurer do
		transition :received => :received_by_treasurer
	end
	
	event :cash do
		transition [:received, :received_by_treasurer] => :cashed
	end

	event :reset_status do
		transition [:cashed, :received_by_treasurer] => :received
	end
	
end

	def mean_is_cheque
		mean == "cheque"
	end

	def save_current_cotisation
		if cotisation == nil then cotisation = Credit::Monthly_cotisation end
	end

	def time_value
		value*31.0/Credit::Monthly_cotisation
	end

private

	# Validation du moyen de paiement
	def mean_is_correct
		# Il doit appartenir à la liste suivante :
		@possible_means = ["cheque", "liquid"]

		@possible_means.each do |possible_mean|
			return true if possible_mean == self.mean
		end
		raise "Le moyen de paiement n'est pas correct."
	end

	def equality_of_values
		paid_value == value
	end

	def set_cached_date
		self.cashed_date = Time.now
	end

	# Mise à jour du crédit de l'utilisateur lors de la création du paiement
	def update_credit
		credit.update_end_of_adhesion
		credit.save
	end

end

app/controllers/payments_controller.rb
# -*- encoding : utf-8 -*-
class PaymentsController < ApplicationController

before_filter :load_adherent

# Charge @payment par id, ainsi que les autorisations du controller
load_and_authorize_resource

  # Get /payments
  def index_all
    @payments = Payment.includes(:adherent, :admin).where(:archived => params[:archived].to_bool)

    respond_to do |format|
      format.html # index_all.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /adherent/id/payments
  # GET /payments.json
  def index
    @payments = Payment.includes(:adherent, :admin).where(:archived => params[:archived].to_bool)

    respond_to do |format|
      if @adherent 
        format.html { render action: "index" }
      else
        format.html { render action: "index_all" }
      end
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = @adherent.credit.payments.build
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
   def create
    @payment = @adherent.credit.payments.build(params[:payment])
    @payment.admin = current_admin

    respond_to do |format|
      if @payment.save

        @payment.create_activity :create, owner: current_admin
        format.json { render json: @payment, status: :created }
      else        
        flash.now[:error] = @payment.errors.full_messages
        format.js { render action: :new}
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update

    respond_to do |format|
      if @payment.update_attributes(params[:payment])

        @payment.create_activity :update, owner: current_admin

        format.js { head :no_content }
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        flash.now[:error] = @payment.errors.full_messages
        format.js { render action: :edit}
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy

    # On archive au lieu de supprimer de la base de donnée
    @payment.update_attribute(:archived, true)
    @payment.create_activity :destroy, owner: current_admin

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  def reload
    @payments = Payment.where(:archived => params[:archived].to_bool)
    respond_to do |format|
      format.html { render partial: "index_table" }
    end
  end

  def cash
    @payment.cash
    @payment.create_activity :update, owner: current_admin
    respond_to do |format|
      format.js { head :no_content }
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  def by_treasurer
    @payment.by_treasurer
    @payment.create_activity :update, owner: current_admin
    respond_to do |format|
      format.js { head :no_content }
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  def reset_status
    @payment.reset_status
    @payment.create_activity :update, owner: current_admin
    respond_to do |format|
      format.js { head :no_content }
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    def load_adherent
      return unless params[:adherent_id]
      if @adherent = Adherent.find(params[:adherent_id])
        @adherent
      end
    end
end

app/helpers/payments_helper.rb
# -*- encoding : utf-8 -*-
module PaymentsHelper
end

app/views/payments/_edit.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3 Edition d'un paiement

	= bootstrap_flash

= simple_form_for @payment, validate: true, remote: true do |f|
	.modal-body
		= render partial: "form", locals: {f: f}  
	.modal-footer
		- if @payment.state == "cashed" or @payment.state == "received_by_treasurer"
			= link_to reset_status_payment_path(@payment.id), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-primary", remote: true do
				Reset
		- if @payment.state == "received"
			= link_to by_treasurer_payment_path(@payment.id), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-primary", remote: true do
				Recevoir
		- if @payment.state == "received" or @payment.state == "received_by_treasurer"
			= link_to cash_payment_path(@payment.id), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-primary", remote: true do
				Encaisser
		= f.submit "Modifier", {class: "btn btn-primary"}

app/views/payments/_form.html.haml
.controls
	.btn-group.choosable
		Moyen de paiement :
		%button.btn.btn-info.active#cheque-btn
			Chèque
		%button.btn#liquid-btn
			Liquide
	.input-append#bank{style: "margin-left: 100px"}
		= f.input_field :bank_name, placeholder: "Banque"
		%span.add-on
			%i.icon-credit-card.inline{rel: "tooltip", title: "Banque", style: "margin-top: 10px"}

.controls

	.input-append
		= f.input_field :value, placeholder: "Valeur à ajouter", value: (if f.object.value == 0 then "" else f.object.value end)
		%span.add-on
			%i.icon-eur.inline{rel: "tooltip", title: "Valeur à ajouter", style: "margin-top: 10px"}

	.input-append
		= f.input_field :paid_value, placeholder: "Valeur réelle", value: (if f.object.paid_value == 0 then "" else f.object.paid_value end)
		%span.add-on
			%i.icon-money.inline{rel: "tooltip", title: "Valeur réelle", style: "margin-top: 10px"}

.controls
	= f.input_field :comment, as: :text, placeholder: "Commentaire. Nécessaire si les deux valeurs du paiements sont différentes.", rows: "4", style: "width: 490px"

	= f.hidden_field :mean, id: "payment_mean"

app/views/payments/_index_table.html.haml
%table#payments
  %thead
    %tr
      %th Etat
      %th Date
      %th Temps ajouté
      %th Valeur ajoutée
      %th Valeur payée
      %th Adhérent
      %th Admin
      %th Moyen de paiement
      %th 
  %tbody
    -@payments.each do |payment|
      %tr
        %td{:class => if payment.state == "received" then "red" elsif payment.state == "received_by_treasurer" then "orange" elsif payment.state == "cashed" then "green" end}
        %td
          %span{:title => payment.created_at.to_i}= payment.created_at.to_s(:short)
        %td
          = payment.time_value.to_s + " jours"
        %td
          = formatted_amount_with_currency(payment.value)
        %td
          = formatted_amount_with_currency(payment.paid_value)
        %td
          = link_to payment.adherent.full_name, payment.adherent
        %td
          = link_to payment.admin.display_name, payment.admin
        %td
          = if payment.mean_is_cheque then "Chèque (#{payment.bank_name})" else "Liquide" end

        %td.actions
          = link_to edit_payment_path(payment.id), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-warning", remote: true do
            %i.icon-pencil.icon-large
            Editer

app/views/payments/_new.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3
		Créer un paiement pour
		= @adherent.full_name

	= bootstrap_flash

= simple_form_for @payment, url: adherent_payments_path(@adherent), validate: true, remote: true do |f|  

	.modal-body

		= render 'form', f: f

	.modal-footer
		= f.submit "Ajouter", {class: "btn btn-primary"}

app/views/payments/_show.html.haml
.modal-header
  %button.close{ type:"button", 'data-dismiss' => "modal"}
    %i.icon-remove

  %h3= @payment.adherent.full_name

.modal-body
  %p
    %b Value:
    = @payment.value
  %p
    %b Paid value:
    = @payment.paid_value
  %p
    %b Mean:
    = @payment.mean
  %p
    %b Comment:
    = @payment.comment
  %p
    %b Archived:
    = @payment.archived

app/views/payments/edit.html.haml
%h1 Editing payment

= render 'form'

= link_to 'Show', @payment
\|
= link_to 'Back', payments_path

app/views/payments/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'edit') %>");

// Tooltips
$("[rel='tooltip']").tooltip();

// Faire disparaitre le modal quand la requête réussie
$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    reload_payments();
  });

// Moyen de paiement
init_buttons();
payment_is_cheque_or_liquid();
choose_button();

app/views/payments/index.html.haml
%h1 Listing payments

%table
  %tr
    %th Value
    %th Paid value
    %th Mean
    %th Comment
    %th Archived
    %th
    %th
    %th

  - @payments.each do |payment|
    %tr
      %td= payment.value
      %td= payment.paid_value
      %td= payment.mean
      %td= payment.comment
      %td= payment.archived
      %td= link_to 'Show', payment
      %td= link_to 'Edit', edit_payment_path(payment)
      %td= link_to 'Destroy', payment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Payment', new_payment_path

app/views/payments/index_all.html.haml
- content_for :title do
  Liste des paiements


#wrapper
  = render partial: 'index_table'

app/views/payments/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new') %>");

// Tooltips
$("[rel='tooltip']").tooltip();

// Faire disparaitre le modal quand la requête réussie
$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
  });

// Moyen de paiement
payment_is_cheque_or_liquid();
choose_button();

app/views/payments/show.html.haml
%p#notice= notice

%p
  %b Value:
  = @payment.value
%p
  %b Paid value:
  = @payment.paid_value
%p
  %b Mean:
  = @payment.mean
%p
  %b Comment:
  = @payment.comment
%p
  %b Archived:
  = @payment.archived

= link_to 'Edit', edit_payment_path(@payment)
\|
= link_to 'Back', payments_path

app/views/payments/show.js.erb
$("#modal-window").html("<%= escape_javascript(render 'show') %>");

$("[rel='tooltip']").tooltip();