config/routes.rb
# -*- encoding : utf-8 -*-
Sapphire::Application.routes.draw do

  match '/synchronisation', :to => "switchs_management#synchronisation"
  resources :logs


  resources :roles


	# En vrac
		get '/computers/reload', :controller => 'computers', :action => 'reload'
		resources :computers, :only => [:index, :show]

		get '/payments/reload', :controller => 'payments', :action => 'reload'
		resources :payments do
			member do
				get 'cash'
				get 'by_treasurer'
				get 'reset_status'
			end
		end

		# Sessions
		delete "deconnexion", to: "sessions#destroy", as: "deconnexion"
		get 'connexion', to: 'sessions#new', as: :connexion

		root to: "activities#index"

	# Les différentes ressources de l'appli

		resources :sessions
		resources :admins

		get '/mailings/reload', :controller => 'mailings', :action => 'reload'
		resources :mailings

		get '/rooms/reload', :controller => 'rooms', :action => 'reload'
		resources :rooms

		get '/adherents/reload', :controller => 'adherents', :action => 'reload'
		get '/adherents/index_discourse', :controller => 'adherents', :action => 'index_discourse'
		resources :adherents do
			member do
				get 'new_discourse'
				put 'create_discourse'
			end
			resources :computers
			resources :payments
			get "credit/destroy"
		end
		
		get '/generic_dns_entries/reload', :controller => 'generic_dns_entries', :action => 'reload'
	  	resources :generic_dns_entries
	  	resources :computer_dns_entries do
			resources :alias_dns_entries
		end
		resources :vlans

		get '/switches/reload', :controller => 'switches', :action => 'reload'
		resources :switches do
			resources :ports
		end
	
end

app/models/generic_dns_entry.rb
# -*- encoding : utf-8 -*-
class GenericDnsEntry < ActiveRecord::Base

scope :not_archived, -> { where(archived: false)}

# Surveillance par la gem public_activity
	include PublicActivity::Common

# Attributs et associations	

	attr_accessible :external, :name, :return, :dns_type

# Avant validation
	
	before_validation do
		self.name = self.name.downcase if self.name.present?
	end
# Validations

	validates :name, presence: true,
		format: { with: /^([a-z0-9_\-\.]+)$/ }
	validates :return, presence: true
	validates :dns_type, presence: true

end

app/controllers/generic_dns_entries_controller.rb
# -*- encoding : utf-8 -*-
class GenericDnsEntriesController < ApplicationController

# Charge @generic_dns_entry par id, ainsi que les autorisations du controller
load_and_authorize_resource 

  # GET /generic_dns_entries
  # GET /generic_dns_entries.json
  def index
    @generic_dns_entries = GenericDnsEntry.where(:archived => params[:archived].to_bool)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @generic_dns_entries }
    end
  end

  # GET /generic_dns_entries/1
  # GET /generic_dns_entries/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @generic_dns_entry }
    end
  end

  # GET /generic_dns_entries/new
  # GET /generic_dns_entries/new.json
  def new
  end

  # GET /generic_dns_entries/1/edit
  def edit
  end

  # POST /generic_dns_entries
  # POST /generic_dns_entries.json
  def create
    @generic_dns_entry = GenericDnsEntry.new(params[:generic_dns_entry])

    respond_to do |format|
      if @generic_dns_entry.save

        @generic_dns_entry.create_activity :create, owner: current_admin

        format.json { render json: @generic_dns_entry, status: :created, location: @generic_dns_entry }
      else
        flash.now[:error] = @generic_dns_entry.errors.full_messages
        format.js { render action: :new}
      end
    end
  end

  # PUT /generic_dns_entries/1
  # PUT /generic_dns_entries/1.json
  def update

    respond_to do |format|
      if @generic_dns_entry.update_attributes(params[:generic_dns_entry])

        @generic_dns_entry.create_activity :update, owner: current_admin

        format.js { head :no_content }
        format.html { redirect_to @generic_dns_entry, notice: 'Generic dns entry was successfully updated.' }
        format.json { head :no_content }
      else
        flash.now[:error] = @mailing.errors.full_messages
        format.js { render action: :edit}
      end
    end
  end

  # DELETE /generic_dns_entries/1
  # DELETE /generic_dns_entries/1.json
  def destroy
    # On archive au lieu de supprimer de la base de donnée
    @generic_dns_entry.update_attribute(:archived, true)
    @generic_dns_entry.create_activity :destroy, owner: current_admin

    respond_to do |format|
      format.html { redirect_to generic_dns_entries_url }
      format.json { head :no_content }
    end
  end

  def reload
    @generic_dns_entries = GenericDnsEntry.where(:archived => params[:archived].to_bool)
    respond_to do |format|
      format.html { render partial: "index_table" }
    end
  end
end

app/helpers/generic_dns_entries_helper.rb
# -*- encoding : utf-8 -*-
module GenericDnsEntriesHelper
end

app/views/generic_dns_entries/_edit.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3 Création d'une entrée DNS

	= bootstrap_flash

= simple_form_for @generic_dns_entry, validate: true, remote: true do |f|

	.modal-body
		= render partial: "form", locals: {f: f}  
	.modal-footer
		= f.submit "Créer", {class: "btn btn-primary"}

app/views/generic_dns_entries/_form.html.haml
.field
	= f.label :dns_type
	= f.text_field :dns_type
.field
	= f.label :name
	= f.text_field :name
.field
	= f.label :return
	= f.text_field :return
.field
	= f.label :external
	= f.check_box :external

app/views/generic_dns_entries/_index_table.html.haml
%table#generic_dns_entries
  %thead
    %tr
      %th Nom
      %th Type
      %th Retour
      %th 
        = link_to new_generic_dns_entry_path, "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-inverse", remote: true do
          %i.icon-plus
          Nouvelle entrée DNS
  %tbody
    -@generic_dns_entries.each do |generic_dns_entry|
      %tr
        %td
          = generic_dns_entry.name
        %td
          = generic_dns_entry.dns_type
        %td
          = generic_dns_entry.return
        %td.actions
          = link_to generic_dns_entry_path(generic_dns_entry), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-success", remote: true do
            %i.icon-eye-open.icon-large
            Voir
          = link_to edit_generic_dns_entry_path(generic_dns_entry), "data-toggle" => 'modal', "data-target" => '#modal-window', class:"btn btn-warning", remote: true do
            %i.icon-pencil.icon-large
            Editer
          = link_to generic_dns_entry_path(generic_dns_entry), class:"btn btn-danger remote-delete", :method => :delete do
            %i.icon-trash.icon-large
            Supprimer

app/views/generic_dns_entries/_new.html.haml
.modal-header
	%button.close{ type:"button", 'data-dismiss' => "modal"}
		%i.icon-remove

	%h3 Création d'une entrée DNS

	= bootstrap_flash

= simple_form_for @generic_dns_entry, validate: true, remote: true do |f|

	.modal-body
		= render partial: "form", locals: {f: f}  
	.modal-footer
		= f.submit "Créer", {class: "btn btn-primary"}

app/views/generic_dns_entries/edit.html.haml
%h1 Editing generic_dns_entry

= render 'form'

= link_to 'Show', @generic_dns_entry
\|
= link_to 'Back', generic_dns_entries_path

app/views/generic_dns_entries/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'edit') %>");

$("[rel='tooltip']").tooltip();

$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    reload_generic_dns_entries();
  });

app/views/generic_dns_entries/index.html.haml
- content_for :title do
  Liste des entrées DNS génériques

#wrapper
  = render partial: 'index_table'

app/views/generic_dns_entries/new.html.haml
%h1 New generic_dns_entry

= render 'form'

= link_to 'Back', generic_dns_entries_path

app/views/generic_dns_entries/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new') %>");

$("[rel='tooltip']").tooltip();

$("form").on("ajax:success", function(event, data, status, xhr){
    $('#modal-window').modal('hide');
    reload_generic_dns_entries();
  });

app/views/generic_dns_entries/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @generic_dns_entry.type
%p
  %b Name:
  = @generic_dns_entry.name
%p
  %b Return:
  = @generic_dns_entry.return
%p
  %b External:
  = @generic_dns_entry.external
%p
  %b Archived:
  = @generic_dns_entry.archived

= link_to 'Edit', edit_generic_dns_entry_path(@generic_dns_entry)
\|
= link_to 'Back', generic_dns_entries_path